import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";
import Footer from "@/components/Home/Footer/Footer";
import ScrollToTop from "@/components/Helper/ScrollToTop";

const fonts = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin-ext']
})

export const metadata: Metadata = {
  title: "Tech Next App",
  description: "Generated by using next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.className} antialiased`}
      >

        <ResponsiveNav />
        {children}
        <Footer />
        <ScrollToTop />

      </body>
    </html>
  );
}
